name: simedi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  gap: ^3.0.1
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

